### ISSUE TITLE
Protein pagination

### ISSUE THREAD

**Issue by zenodeapp** [zenodeapp/protein-crud#8]
Explore the idea of paging protein sets together in a single contract. 

Currently seeing two ways to fix this:
1. Either by explicitly giving each protein a page number (by inserting them under a page index or giving each Protein Struct a page ID).
2. Or, by creating a function with parameters like page number and amount of results per page which returns a 'slice' of the dataset.

**Comment by GenesisL1** [comment]
Another option is to make separate data "indexing" contracts with optimal count of items (e.g. 1000, or 10000) and router contract where indexers contracts may be "added". This also apply to #9
